name: CI Testing

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8.x
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: npm install and test
      run: |
        npm ci
        npm test
        echo "fuck yeah!"
      env:
        CI: true
